### ISSUE TITLE
Ideas - Music player should respect Jukebox/Note blocks volume slider

### ISSUE THREAD

**Issue by aking4125** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#10]
This is a rather minor request. If it's at all possible for the music player to respect the Jukebox/Note blocks, or, have it's own slider to fine tune the music volume. It only respects the master volume slider.

I understand if this is perhaps a limit on the mod itself.

Also, would it be possible to somehow stop the normal background music from overlapping or playing while the music player is running?

**Comment by SokyranTheDragon** [comment]
There should be an option to change the music player volume settings in the mod options, in position named `Base settings` and it starts at 30% of volume. It was originally tied to Jukebox volume, but I decided to make it a separate option.

Please note, changing that option while a song is already playing won't have an effect until another one starts playing.


About stopping the background music, it's something I want to do but it seems like there's no obvious, easy way to do it. Because of that, I'll leave that issue open for now.
