### ISSUE TITLE
Missing recipe for egg sorter

### ISSUE THREAD

**Issue by blarghhh** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#14]
the egg sorter seems to be missing the recipe even though hatchery is enabled in the config. what is the recipe to craft it so that it can tested whether it's a bug in jei or not

![2020-02-13_08 04 31](https://user-images.githubusercontent.com/6789845/74390566-ad41db00-4e3c-11ea-9dfd-7091f65ea1e2.png)

**Comment by SokyranTheDragon** [comment]
Thanks for the report, I'll look into this. I've got an idea where I could look for the potential issue.

The recipe for it should be an egg from Hatchery, surrounded by wooden planks of any type.

**Comment by SokyranTheDragon** [comment]
Hmm... It seems to be working fine on my side. Are you using the most recent version of the mod? And could you share which mods are you using? That would make finding the issue easier.

**Comment by blarghhh** [comment]
playing it in a modpack, awakening - sky of diamonds 1.11.1 on a server.

the version of the mod should be mia-1.12.2-0.1.3a.jar according to what i have client side

**Comment by blarghhh** [comment]
![2020-02-15_05 37 59](https://user-images.githubusercontent.com/6789845/74569461-6cb99d00-4fb5-11ea-98e7-c2167d6795ac.png)
![2020-02-15_05 37 35](https://user-images.githubusercontent.com/6789845/74569466-6e836080-4fb5-11ea-9956-4b1a5a939447.png)

tried in creative SSP, didnt craft

**Comment by SokyranTheDragon** [comment]
Investigating this issue is sadly taking longer than I'd like as my PC is having issues handling the mod pack. I really hope I'll be able to find the cause issue and fix it.

**Comment by blarghhh** [comment]
alright. good luck

**Comment by SokyranTheDragon** [comment]
I've managed to find and fix the issue. The fix should hopefully be up within the next few hours, as I want to make a few more small improvements and fixes.

For personal, single-player play it's possible to update it manually, however when playing with the mod pack and especially on the server, it'll require the server owners and mod pack developers to update the mod. One workaround that could work if it's not something that could happen would be adding the recipe through CraftTweaker (assuming it gets synced with the client).

For an explanation of this bug - basically, due to an issue with one of the recipes, Minecraft/Forge decided to not load any recipe from this mod at all.
