### ISSUE TITLE
Debug.log ERROR: Couldn't load loot table mia:mocreatures/

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#31]
In [my modpack ](https://github.com/Krutoy242/Enigmatica2Expert-Extended) i have 77 errors in debug.log file started with:
```java
[Server thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager]: Couldn't load loot table mia:mocreatures/passive/ostrich/ostrich_6 from jar:file:/D:/mc_client/Instances/Enigmatica2Expert%20-%20Extended/mods/mia-1.12.2-0.2.1c.jar!/assets/mia/loot_tables/mocreatures/passive/ostrich/ostrich_6.json
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'mocreatures:heartdarkness'
```

They flooding debug.log, so i would like to remove them.
My modpack dont have `mocreatures` mod, so i dont know why MIA add this loot tables from the first place.

[debug.log](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/7861356/debug.zip)

**Comment by SokyranTheDragon** [comment]
Hmm... From what I can see, those loot tables aren't ever loaded by my mod. It seems like it's LootTweaker trying to load those loot tables. Those are completely untouched otherwise by my mod (unless you have Mo' Creatures, obviously).

I suppose it would be possible to change it on my end, but it would be rather tedious and time consuming task. I might do it at some point, but I'm not sure when.

I wonder if it would be possible to get Loot Tweaker to ignore those? I've never used it before so I'm not sure.

**Comment by Krutoy242** [comment]
As far as i know, loot tables loaded **before** LootTweaker can tweak them. So, with LT i **can't** remove or add loot from `mia:mocreatures` or other erroring tables.
